"""empty message

Revision ID: 051b8b5d6a1b
Revises: 5de24ecc04c8
Create Date: 2024-02-01 19:31:27.146599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051b8b5d6a1b'
down_revision = '5de24ecc04c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appearances_episode_id_episodes'), 'episodes', ['episode_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appearances_guest_id_guests'), 'guests', ['guest_id'], ['id'])

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('episode_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_column('episode_number')
        batch_op.drop_column('air_date')

    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appearances_guest_id_guests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appearances_episode_id_episodes'), type_='foreignkey')
        batch_op.drop_column('guest_id')
        batch_op.drop_column('episode_id')

    # ### end Alembic commands ###
