"""empty message

Revision ID: 497bb35b487c
Revises: 18dea8b5bef3
Create Date: 2024-02-01 19:46:58.020604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497bb35b487c'
down_revision = '18dea8b5bef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_date', sa.String(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('air_date')

    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
