"""empty message

Revision ID: bca03f913541
Revises: 051b8b5d6a1b
Create Date: 2024-02-01 19:35:51.610534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca03f913541'
down_revision = '051b8b5d6a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.drop_column('air_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_date', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
